name: Test IBM Cloud CLI Action
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure IBM Cloud CLI
        uses: ./
        with:
          ibm-cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
          ibm-cloud-region: "us-south"
          ibm-cloud-cli-plugins: "container-registry,cloud-object-storage"
